spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  jackson:
    serialization:
      fail-on-empty-beans: false


  datasource:
    url: jdbc:mysql://localhost:3306/starTalkDB
    username: root
    password: Fredom1808
    driver-class-name: com.mysql.cj.jdbc.Driver

#  liquibase:
#    enabled: false
#    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8080